version: 2
jobs:
  build:
    docker:
      - image: ninjaahhh/circleci-goquarkchain:v0.0.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v2-{{ checksum "go.sum" }}
      # Build qkchash c++
      - run: cd consensus/qkchash/native && make && cd -
      - run: go vet ./...
      - run: go test -timeout 1m ./... -gcflags=-l
      - save_cache:
          key: go-mod-v2-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  check-db:
    docker:
      - image: quarkchaindocker/goquarkchain

    steps:
      - run:
          name: check remote stats
          command: |
            apt-get update && apt-get install sshpass
            ssh-keygen -R 167.71.117.195
            sshpass -p $CheckDBHostPassword scp -o StrictHostKeyChecking=no root@167.71.117.195:/tmp/status.txt ./
            echo `date +"%Y-%m-%d %H:%M:%S"`
            echo "status.txt"
            cat status.txt




workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - check-db
  nightly:
    triggers:
      - schedule:
          cron: "30 * * * *"
          filters:
            branches:
              only:
                - fix-ci
    jobs:
      - build
      - check-db:
          requires:
            - build
